apiVersion: v1
kind: Pod
metadata:
  name: zulip
spec:
  containers:
  - name: database
    image: zulip/zulip-postgresql:14
    envFrom:
    - configMapRef:
        name: postgres-vars
        optional: False
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres-data
  - name: zulip
    image: zulip/docker-zulip:7.0-0
    ports:
    - containerPort: 80
      hostPort: 80
    - containerPort: 443
      hostPort: 443
    envFrom:
    - configMapRef:
        name: zulip-vars
        optional: False
    volumeMounts:
    - mountPath: /data
      name: zulip-data
    - mountPath: /var/log/zulip
      name: zulip-logs
  - name: redis
    image: redis:alpine
    args:
    - sh
    - -euc
    - |
      echo "requirepass '$REDIS_PASSWORD'" > /etc/redis.conf
      exec redis-server /etc/redis.conf
    envFrom:
    - configMapRef:
        name: redis-vars
        optional: False
    volumeMounts:
    - mountPath: /data
      name: redis-data
  - name: memcached
    image: memcached:alpine
    args:
    - sh
    - -euc
    - |
      echo 'mech_list: plain' > "$SASL_CONF_PATH"
      echo "zulip@$HOSTNAME:$MEMCACHED_PASSWORD" > "$MEMCACHED_SASL_PWDB"
      echo "zulip@localhost:$MEMCACHED_PASSWORD" >> "$MEMCACHED_SASL_PWDB"
      exec memcached -S
    envFrom:
    - configMapRef:
        name: memcached-vars
        optional: False
  - name: rabbitmq
    image: rabbitmq:3.7
    envFrom:
    - configMapRef:
        name: rabbitmq-vars
        optional: False
    volumeMounts:
    - mountPath: /var/lib/rabbitmq
      name: rabbitmq-data
  volumes:
  - hostPath:
      path: /opt/zulip/rabbitmq
    name: rabbitmq-data
  - hostPath:
      path: /opt/zulip/redis
    name: redis-data
  - hostPath:
      path: /opt/zulip/postgresql/data
    name: postgres-data
  - hostPath:
      path: /opt/zulip/data
    name: zulip-data
  - hostPath:
      path: /opt/zulip/logs
    name: zulip-logs