---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zulip-vars
data:
    DB_HOST: localhost
    DB_HOST_PORT: "5432"
    DB_USER: zulip
    SECRETS_email_password: $EMAIL_PASSWORD
    SECRETS_memcached_password: $MEMCACHED_PASSWORD
    SECRETS_postgres_password: $POSTGRES_PASSWORD
    SECRETS_redis_password: $REDIS_PASSWORD
    SECRETS_rabbitmq_password: $RABBITMQ_PASSWORD
    SECRETS_secret_key: $ZULIP_SECRET_KEY
    SECRETS_social_auth_gitlab_secret: $GITLAB_APPLICATION_SECRET
    SETTING_EMAIL_HOST: $EMAIL_HOST
    SETTING_EMAIL_HOST_USER: $EMAIL_HOST_USER
    SETTING_EMAIL_PORT: "$EMAIL_PORT"
    SETTING_EMAIL_USE_SSL: $EMAIL_USE_SSL
    SETTING_EMAIL_USE_TLS: $EMAIL_USE_TLS
    SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS: $ADD_TOKENS_TO_NOREPLY_ADDRESS
    SETTING_TOKENIZED_NOREPLY_EMAIL_ADDRESS: $TOKENIZED_NOREPLY_EMAIL_ADDRESS
    SETTING_NOREPLY_EMAIL_ADDRESS: $NOREPLY_EMAIL_ADDRESS
    SETTING_EXTERNAL_HOST: $EXTERNAL_HOST_URL
    SETTING_MEMCACHED_LOCATION: localhost:11211
    SETTING_RABBITMQ_HOST: localhost
    SETTING_REDIS_HOST: localhost
    SETTING_SOCIAL_AUTH_GITLAB_API_URL: $GITLAB_API_URL
    SETTING_SOCIAL_AUTH_GITLAB_KEY: $GITLAB_KEY
    SETTING_ZULIP_ADMINISTRATOR: $ZULIP_ADMINISTRATOR_EMAIL
    SSL_CERTIFICATE_GENERATION: $SSL_CERTIFICATE_GENERATION
    ZULIP_AUTH_BACKENDS: $AUTH_BACKENDS

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-vars
data:
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: zulip
    POSTGRES_USER: zulip

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-vars
data:
    REDIS_PASSWORD: $REDIS_PASSWORD

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-vars
data:
    MEMCACHED_PASSWORD: $MEMCACHED_PASSWORD
    MEMCACHED_SASL_PWDB: /home/memcache/memcached-sasl-db
    SASL_CONF_PATH: /home/memcache/memcached.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-vars
data:
    RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
    RABBITMQ_DEFAULT_USER: zulip
