---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zulip-vars
data:
    DB_HOST: localhost
    DB_HOST_PORT: "5432"
    DB_USER: zulip
    SECRETS_email_password: emailpasswordhere
    SECRETS_memcached_password: 15fba8506eda24a70db913584e321b74
    SECRETS_postgres_password: 5b189b5a37fc4725af9245cb799c425c
    SECRETS_redis_password: fff2ef8991a938002ca13b8ae5e09374
    SECRETS_rabbitmq_password: 68ff61999d15232816f7dc658ca20ce0
    SECRETS_secret_key: 35c6124bb19c7fe1d8730b80703bdd50
    SECRETS_social_auth_gitlab_secret: gitlabsecrethere
    SETTING_EMAIL_HOST: localhost.localdomain
    SETTING_EMAIL_HOST_USER: user@localhost.localdomain
    SETTING_EMAIL_PORT: "587"
    SETTING_EMAIL_USE_SSL: False
    SETTING_EMAIL_USE_TLS: True
    SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS: True
    SETTING_TOKENIZED_NOREPLY_EMAIL_ADDRESS: noreply-{token}@localhost.localdomain
    SETTING_NOREPLY_EMAIL_ADDRESS: noreply@localhost.localdomain
    SETTING_EXTERNAL_HOST: https://localhost
    SETTING_MEMCACHED_LOCATION: localhost:11211
    SETTING_RABBITMQ_HOST: localhost
    SETTING_REDIS_HOST: localhost
    SETTING_SOCIAL_AUTH_GITLAB_API_URL: https://gitlab.example.com/api
    SETTING_SOCIAL_AUTH_GITLAB_KEY: gitlabkeyhere
    SETTING_ZULIP_ADMINISTRATOR: user@localhost.localdomain
    SSL_CERTIFICATE_GENERATION: self-signed
    ZULIP_AUTH_BACKENDS: EmailAuthBackend,GitLabAuthBackend

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-vars
data:
    POSTGRES_PASSWORD: 5b189b5a37fc4725af9245cb799c425c
    POSTGRES_DB: zulip
    POSTGRES_USER: zulip

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-vars
data:
    REDIS_PASSWORD: fff2ef8991a938002ca13b8ae5e09374

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: memcached-vars
data:
    MEMCACHED_PASSWORD: 15fba8506eda24a70db913584e321b74
    MEMCACHED_SASL_PWDB: /home/memcache/memcached-sasl-db
    SASL_CONF_PATH: /home/memcache/memcached.conf

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-vars
data:
    RABBITMQ_DEFAULT_PASS: 68ff61999d15232816f7dc658ca20ce0
    RABBITMQ_DEFAULT_USER: zulip


